Aselect distinct NOMBRE_LOCAL from PETRO.REPORTE_PRECIO_LISTA
select distinct DESCRIPCION_PRODUCTO from PETRO.REPORTE_PRECIO_LISTA


select * from PETRO.REPORTE_PRECIO_LISTA where NOMBRE_LOCAL='EESS-PUENTE PIEDRA' and DESCRIPCION_PRODUCTO='DIESEL DB5'



SELECT NOMBRE_GRIFO,FECHA,TOTAL_SALIDA_DB5,TOTAL AS TOTAL_WEB_ACTIVA
 FROM [PETRO].[PARTE_DIARIO_TOTAL] A
INNER JOIN #TMEP_VENTA B ON B.FECHA_TURNO=A.FECHA
WHERE TOTAL_SALIDA_DB5<>TOTAL

SELECT * FROM #TMEP_VENTA
SELECT * FROM  [PETRO].[CONFIGURACION_PARTE_DIARIO_TOTAL] 

SELECT * FROM [PETRO].[PARTE_DIARIO_TOTAL] 

TRUNCATE TABLE [PETRO].[PARTE_DIARIO_TOTAL] 